https://www.perplexity.ai/search/045ecda7-23bf-4d76-9155-fcb886e2425e

In [1]:
import numpy as np
np.random.random()
np.random.random(3)
np.random.random(size=3)
np.random.random((3,4))
np.random.random(size=(3,4))

array([[0.71686159, 0.73782444, 0.90819237, 0.37712181],
       [0.38025498, 0.02722683, 0.02148284, 0.95611113],
       [0.97395448, 0.60700711, 0.95284165, 0.59203629]])

In [7]:
from numpy.random import normal

normal_value = normal (size=(3,4))
#nparray常用的實體屬性
type(normal_value)
normal_value.ndim
normal_value.size
normal_value.shape
normal_value.dtype

dtype('float64')

In [8]:
#ndarray,陣列運算
normal_value * 10

array([[ -2.16951228,  -6.38481682,  -4.04161553,  -9.22362534],
       [  4.08326009, -12.31075654,  11.12371757,   0.63824752],
       [ 16.98752945,  10.49703464,   2.8204788 ,  -4.78253687]])

In [12]:
#ndarray,的統計
normal_value.sum()
normal_value.sum(axis=0)
normal_value.sum(axis=1)

array([-2.181957  ,  0.35344686,  2.5522506 ])